// This file is auto-generated by @hey-api/openapi-ts

export const dto_AuthTokensSchema = {
    type: 'object',
    properties: {
        access: {
            '$ref': '#/definitions/dto.Token'
        },
        refresh: {
            '$ref': '#/definitions/dto.Token'
        }
    }
} as const;

export const dto_HTTPErrorSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const dto_TokenSchema = {
    type: 'object',
    properties: {
        expires: {
            type: 'string'
        },
        token: {
            type: 'string'
        }
    }
} as const;

export const dto_UserRegisterSchema = {
    type: 'object',
    required: ['email', 'password', 'username'],
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const dto_UserRegisterResponseSchema = {
    type: 'object',
    properties: {
        tokens: {
            '$ref': '#/definitions/dto.AuthTokens'
        },
        user: {
            '$ref': '#/definitions/dto.UserReturn'
        }
    }
} as const;

export const dto_UserReturnSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        verified_email: {
            type: 'boolean'
        }
    }
} as const;