// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { PostUserRegisterData, PostUserRegisterError, PostUserRegisterResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Register a new user
 * Register a new user using his email, username and password. Returns his ID, email, username, verifiedEmail boolean variable and role
 */
export const postUserRegister = <ThrowOnError extends boolean = false>(options: Options<PostUserRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostUserRegisterResponse, PostUserRegisterError, ThrowOnError>({
        ...options,
        url: '/user/register'
    });
}